### ISSUE TITLE
Stations thumbnails not appearing anymore

### ISSUE THREAD

**Issue by TheFighter137** [maunalinux/shortwave#3]
Hello,

Since I reinstalled Shortwave a few days ago, the thumbnails/logos of any radio station do not appear anymore. A month ago, they were still here. Is there any way to fix this issue please ?

![image](https://github.com/user-attachments/assets/3ea52fa9-a656-4da5-a796-49f957b51e4f)

**Comment by maunalinux** [comment]
Hello,

I was testing and even reinstalled Shortwave and it is working normally. In case of repairing any errors in the code, you have to contact the author directly, because I only maintain the version that works on Mauna based on Debian Bookworm.

Try to install Shortwave via Flatpak which is available in our App Store. Search for Software Manager on your Mauna and search for Shortwave and then just install the latest version of the application.

![shortwave](https://github.com/user-attachments/assets/dbc10058-3a5d-4dce-b3dc-1ec848097d47)

**Comment by TheFighter137** [comment]
Hello,

Apologies, I genuinely thought at first this was the "general" page for Shortwave, but actually I found the real one, which is on GitLab.
For now I have never heard of Mauna, but I will look into it.
Thanks for your answer !
